// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	gax "github.com/googleapis/gax-go/v2"

	mock "github.com/stretchr/testify/mock"

	secretmanager "google.golang.org/genproto/googleapis/cloud/secretmanager/v1"
)

// GoogleSecretsManagerAPI is an autogenerated mock type for the GoogleSecretsManagerAPI type
type GoogleSecretsManagerAPI struct {
	mock.Mock
}

// AccessSecretVersion provides a mock function with given fields: ctx, req, opts
func (_m *GoogleSecretsManagerAPI) AccessSecretVersion(ctx context.Context, req *secretmanager.AccessSecretVersionRequest, opts ...gax.CallOption) (*secretmanager.AccessSecretVersionResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *secretmanager.AccessSecretVersionResponse
	if rf, ok := ret.Get(0).(func(context.Context, *secretmanager.AccessSecretVersionRequest, ...gax.CallOption) *secretmanager.AccessSecretVersionResponse); ok {
		r0 = rf(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secretmanager.AccessSecretVersionResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *secretmanager.AccessSecretVersionRequest, ...gax.CallOption) error); ok {
		r1 = rf(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewGoogleSecretsManagerAPI interface {
	mock.TestingT
	Cleanup(func())
}

// NewGoogleSecretsManagerAPI creates a new instance of GoogleSecretsManagerAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGoogleSecretsManagerAPI(t mockConstructorTestingTNewGoogleSecretsManagerAPI) *GoogleSecretsManagerAPI {
	mock := &GoogleSecretsManagerAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
