// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	gax "github.com/googleapis/gax-go/v2"

	mock "github.com/stretchr/testify/mock"

	secrets "google.golang.org/genproto/googleapis/cloud/secrets/v1beta1"
)

// GoogleSecretsManagerAPI is an autogenerated mock type for the GoogleSecretsManagerAPI type
type GoogleSecretsManagerAPI struct {
	mock.Mock
}

// AccessSecretVersion provides a mock function with given fields: ctx, req, opts
func (_m *GoogleSecretsManagerAPI) AccessSecretVersion(ctx context.Context, req *secrets.AccessSecretVersionRequest, opts ...gax.CallOption) (*secrets.AccessSecretVersionResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *secrets.AccessSecretVersionResponse
	if rf, ok := ret.Get(0).(func(context.Context, *secrets.AccessSecretVersionRequest, ...gax.CallOption) *secrets.AccessSecretVersionResponse); ok {
		r0 = rf(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secrets.AccessSecretVersionResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *secrets.AccessSecretVersionRequest, ...gax.CallOption) error); ok {
		r1 = rf(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
